name: "deploy pages two"

on: [workflow_dispatch]

jobs:
  deploy_pages_two:
    name: "deploy pages",
    runs-on: "ubuntu-latest"
    steps:
      - name: "Publish report to GH pages"
          uses: sede-open/github-pages-deploy-action@4.1.4
          with:
            branch: pages
            folder: another-test-folder